### ISSUE TITLE
Datadog dashboard for candle generation stats

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/trade-executor#117]
Have a dashboard that shows data coming to DataDog from candle parquet tasks

- Tag by the candle time frame (1d, 4d, etc.)
- How long the task took
- How many megabytes of data got generated

[See here](https://github.com/tradingstrategy-ai/oracle/blob/master/dex_ohlcv/writer/parquet_candles.py#L344).

**Comment by plamut** [comment]
PR merged and deployed, let's see f we have some stats already...

**Comment by plamut** [comment]
Dashboards added. Realized that chain info is missing, which we need, will add that tag.

**Comment by plamut** [comment]
PR merged, will update the dashboards tomorrow when new stats arrive.

**Comment by plamut** [comment]
Stats are not arriving at the moment, it appears that the data precompute tasks are not running.

**Comment by miohtama** [comment]
Let's close now and reopen when we need better stats. Current dashboard is good enough.
