### ISSUE TITLE
Check technical indicator and other symbol timing on the pricing chart visualisations

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/trade-executor#131]
Currently we are displaying 1h strategy decision cycle on 15 minutes candles.

For the example strategy, trades happen when fast and slow EMAs cross over. 

Because of the mismatch between candle timeframes, "buy" market is not on the actual timestamp when lines cross visually. 

Investigate if we have some sort of data offset issue, or is this just the nature of charting and not easily fixable.

![image](https://user-images.githubusercontent.com/49922/206691818-d2d0d7c6-dc7c-4b51-9f6b-27c4531c4009.png)

**Comment by AlexTheLion123** [comment]
postponed for now until we get the real time execution working better

**Comment by AlexTheLion123** [comment]
@miohtama Is this still an issue

**Comment by miohtama** [comment]
@AlexTheLion123 Also there is issue related to indicator being 1 candle off in the backesting
