### ISSUE TITLE
Return strict JSON from all API endpoints

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#135]
# Overview

The `json.dumps()` method has an `allow_nan` param that defaults to `True`. This can result in `NaN` values in a JSON payload, which are not strictly valid JSON and likely to cause parsing errors by many clients (including `frontend`).

Audit existing APIs to ensure that they all set `allow_nan` to `False`.

## Details

On `2022-12-12`, `frontend` was reporting `500` errors when loading `strategies`. This was traced back to an error in the `metadata` JSON payload for the `pancake-eth-usd-sma` strategy.

This was fixed for the metadata endpoint – see:
https://github.com/tradingstrategy-ai/trade-executor/blob/3bddf04458bdfdaeb8d85aa583f455622f4f38a2/tradeexecutor/webhook/api.py#L67

To ensure this doesn't occur with other endpoints / datasets, a similar fix should be applied to other endpoints.

**Comment by AlexTheLion123** [comment]
@kenkunz Checking if this is still an issue since opened a while ago?
