### ISSUE TITLE
Uniswap v3 example strategy

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/trade-executor#140]
Create an example strategy that trades using Uniswap v3 data

- [x] #155
     - Check that data on the website live charts is correct
     - Check that we have good pair and exchange information in datasets
     - After the notebook is ready place it in the documentation
     - Any missing enums, exchange slugs and such need to be added to the code
- [x] #142
     - Apply any of existing strategies using ETH/USD price action
- [ ] #154
     - Create an example script in `web3-ethereum-defi` repo that performs a single swap on Uniswap v3 e.g. USDC->WETH->USDC for 0.50 USD
     - Create a router configuration for Uniswap v3 swaps
     - Create live price feed

**Comment by miohtama** [comment]
@hieuh25 New ticket for enabling Uniswap v3 on Polygon

**Comment by AlexTheLion123** [comment]
@miohtama For backtesting with uni v3, in addition to some minor bug fixes, there seems to be a data issue. This line is giving an error:

https://github.com/tradingstrategy-ai/trading-strategy/blob/334a228c3dde706d7b411dbd7afecd9f039264c7/tradingstrategy/transport/jsonl.py#L228

Because the v3 data looks like this:
```
pair_id   timestamp         open         high          low        close  \
0  2697585  1620273600  3454.024272  3454.024272  3429.245846  3429.245846   
1  2697585  1620288000  3434.393317  3471.336773  3434.393317  3459.554858   
2  2697585  1620302400  3473.420096  3535.797366  3473.420096  3527.674783   
3  2697585  1620316800  3531.557166  3560.277503  3452.297778  3452.297778   
4  2697585  1620331200  3456.097205  3509.379398  3456.097205  3509.379398   

   buy_volume   sell_volume  start_block  end_block  exchange_rate  
0         0.0   5172.881978     12379175   12379284            1.0  
1         0.0   9792.869118     12380169   12380336            1.0  
2         0.0  46121.208984     12380870   12381657            1.0  
3         0.0  82165.829352     12381777   12382440            1.0  
4         0.0  46051.120620     12383255   12383399            1.0 
```

Which doesn't include `buys` and `sells` as required:

https://github.com/tradingstrategy-ai/trading-strategy/blob/334a228c3dde706d7b411dbd7afecd9f039264c7/tradingstrategy/candle.py#L112-L127

**Comment by AlexTheLion123** [comment]
> @miohtama For backtesting with uni v3, in addition to some minor bug fixes, there seems to be a data issue. This line is giving an error:
> 
> [tradingstrategy-ai/trading-strategy@`334a228`/tradingstrategy/transport/jsonl.py#L228](https://github.com/tradingstrategy-ai/trading-strategy/blob/334a228c3dde706d7b411dbd7afecd9f039264c7/tradingstrategy/transport/jsonl.py#L228)
> 
> Because the v3 data looks like this:
> 
> ```
> pair_id   timestamp         open         high          low        close  \
> 0  2697585  1620273600  3454.024272  3454.024272  3429.245846  3429.245846   
> 1  2697585  1620288000  3434.393317  3471.336773  3434.393317  3459.554858   
> 2  2697585  1620302400  3473.420096  3535.797366  3473.420096  3527.674783   
> 3  2697585  1620316800  3531.557166  3560.277503  3452.297778  3452.297778   
> 4  2697585  1620331200  3456.097205  3509.379398  3456.097205  3509.379398   
> 
>    buy_volume   sell_volume  start_block  end_block  exchange_rate  
> 0         0.0   5172.881978     12379175   12379284            1.0  
> 1         0.0   9792.869118     12380169   12380336            1.0  
> 2         0.0  46121.208984     12380870   12381657            1.0  
> 3         0.0  82165.829352     12381777   12382440            1.0  
> 4         0.0  46051.120620     12383255   12383399            1.0 
> ```
> 
> Which doesn't include `buys` and `sells` as required:
> 
> [tradingstrategy-ai/trading-strategy@`334a228`/tradingstrategy/candle.py#L112-L127](https://github.com/tradingstrategy-ai/trading-strategy/blob/334a228c3dde706d7b411dbd7afecd9f039264c7/tradingstrategy/candle.py#L112-L127)
> 
> ```
> KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'buys' not found in columns."
> ```

Moved disucssion to https://github.com/tradingstrategy-ai/trade-executor/issues/142

**Comment by AlexTheLion123** [comment]
live strategy can be found on #222
