### ISSUE TITLE
adjust summary stats

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#157]
adjust the `calculate_summary_statistics` method so that it no longer need to use `stop_loss_pct` since some of these stats are calculated in position class. See [this discussion](https://github.com/tradingstrategy-ai/trade-executor/pull/90#discussion_r1050626024) and [this PR](https://github.com/tradingstrategy-ai/trade-executor/pull/149)

**Comment by AlexTheLion123** [comment]
@miohtama In order to access some of the methods and properties that you made in the linked PR above in the `calculate_summary_statistics` method, I'm trying to use to convert the `TradePosition` instance to a `TradingPosition` instance using `self.portfolio.get_position_by_id(position.position_id)`. However due to this line, the position id's are different between the two. Wondering if this is a bug that needs to be fixed?  

https://github.com/tradingstrategy-ai/trade-executor/blob/f078b3cd58ef032586f896a3a62c2b392a7424e3/tradeexecutor/analysis/trade_analyser.py#L133

For my purposes, I can get around this by using 

```for position in self.portfolio.get_all_positions():```

instead of 

https://github.com/tradingstrategy-ai/trade-executor/blob/f078b3cd58ef032586f896a3a62c2b392a7424e3/tradeexecutor/analysis/trade_analyser.py#L534

Should I try to fix the bug if it is a bug, or should I just use ```for position in self.portfolio.get_all_positions():```?

**Comment by miohtama** [comment]
Please try to fix the bug and use the same position ids everywhere.
