### ISSUE TITLE
Trade executor frontend statistics updates

### ISSUE THREAD

**Issue by hieuh25** [tradingstrategy-ai/trade-executor#17]
Related to https://github.com/tradingstrategy-ai/trade-executor-frontend/issues/4

We need the following stats:
- [x] Strategy's base currency (USDC)
- [ ] Net profit % (from the beginning, past 7 days, past 30 days) i.e. Gross Profit−Gross Loss = Net Profit
- [ ] Max drawdown (%) i.e. https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
- [ ] Assets under management (USD)
- [ ] AUM growth in last 30 days (%)
- [x] Trade win rate (%) e.g. 77 Winning Trades / 140 Total Trades = 55% Win Percentage
- [ ] Average trade net profit i.e. total net profit / total number of trades
- [ ] Profit factor i.e. Gross profit/Gross loss (including fees and commissions) for the entire trading period
- [x] Number of closed trades
- [ ] Number of traders/investors in the strategy

**Comment by miohtama** [comment]
@hieuh25 is this still under your work?

We can pass to @kenjinezumi if needed

**Comment by hieuh25** [comment]
> @hieuh25 is this still under your work?
> 
> We can pass to @kenjinezumi if needed

Not at the moment, we can merge this one to #31 since there are overlapping stats then @kenjinezumi can take over

**Comment by kenjinezumi** [comment]
I am on it
