### ISSUE TITLE
Dynamic Stop loss, Take profit and Trail stop

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/trade-executor#174]
New feature addition of dynamic Stop Loss, Take Profit, and Trail stop

**Logic**

- Traders can enhance the efficacy of a stop-loss by pairing it with a trailing, which is a trade order where the stop-loss price isn't fixed at a single, absolute price, but is rather set at a certain percentage below the current market price. When the price increases, it drags the trailing stop along with it. Then when the price finally stops rising, the new stop-loss price remains at the level it was dragged to, thus automatically protecting an investor's downside, while locking in profits as the price reaches new highs. 

- Here is an example, the entry price of WBNBUSDC is 20,000, the stop loss is at 0.95 and the take profit is at 1.05, as per our current system settings. When the market starts moving up the trailing stop trails the market price after a 0.01 change in market price (1% price movement), which can be set as a variable. Then the system can continuously trail the market movement as it happens. 

- Let there be another variable that triggers the removal of take profit if it has been enabled at the same time as the trailing stop. For example, if the market has moved by 0.03 (3%) from the entry price, then it would trigger the removal of the take profit and move the stop loss above the entry point by the commission percent just to protect the investor. 
- There is a need to also determine which trailing stop we are using. Is it a static point trailing stop, dynamic points trailing stop, or is it a moving average trailing stop.

**Comment by AlexTheLion123** [comment]
Support for trailing stop loss (percentage only) has been added https://github.com/tradingstrategy-ai/trade-executor/pull/296

**Comment by AlexTheLion123** [comment]
Can we close @miohtama
