### ISSUE TITLE
create fee enums

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#209]
A fee enum has been created in the eth_defi package. However, that is only for `BPS`. Different parts of the codebase seem to be using different types of fee input (there is also `multiplier` and `raw_fee`). This can be very confusing 

- [ ] Create enums for `multipliers` and `raw_fee` inputs (bps enum already created).
- [ ] Make sure all fees in tradexecutor and eth_defi use fee enums

**Comment by miohtama** [comment]
Let's try to standardise to float `0...1` instead. Float is accurate enough to represent any fee tier and much more user friendly.
