### ISSUE TITLE
pancake-eth-usd-sma metadata and state values differ

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#213]
# Issue

The values that represent the **total current asset value** of a strategy differ between the `metadata` endpoint and the `state` endpoint. The appears to only be the case for the `pancake-eth-usd-sma` strategy.

## Details

The source for **total current asset value** from the `metadata` API payload is:
```
summary_statistics.current_value
```

The source for **total current asset value** from the `state` API payload is:
```
stats.portfolio.at(-1).total_equity
```

See: https://github.com/tradingstrategy-ai/trade-executor-frontend/blob/master/src/lib/state/stats.ts#L20

## Reproduction – UI

The following screenshots are from Tuesday Feb 14 2023 18:30 CET.

<table>
<thead>
<tr>
<th>Strategy Index</th>
<th>Strategy details</th>
</thead>
<tbody>
<tr>
<td>
<img width="1235" alt="strategies index" src="https://user-images.githubusercontent.com/35901/218809307-922ee9d4-6d8b-43ee-a422-51f3c3c297de.png"></td>
<td>
<img width="1238" alt="pancake-eth-usd-sma" src="https://user-images.githubusercontent.com/35901/218809621-598df192-2960-4913-8c8c-83a34c179620.png">
</td>
</tr>
</tbody>
</table>

## Reproduction - API

The following requests / responses are from Tuesday Feb 14 2023 18:30 CET. The `jq` utility is required to extract the relevant attributes.

**`metadata` API**
```bash
curl https://pancake-eth-usd-sma.tradingstrategy.ai/metadata | jq '.summary_statistics.current_value'
=> 416.37669296145924
```

**`state` API**
```bash
curl https://pancake-eth-usd-sma.tradingstrategy.ai/state | jq '.stats.portfolio[-1].total_equity'
=> 422.8136985720132
```

**Comment by miohtama** [comment]
Related to #251
