### ISSUE TITLE
Missing position statistics on MATIC-USD EMA on Quickswap

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#240]
See tradingstrategy-ai/frontend#387

The `frontend` issue has been fixed by making the more resilient to missing data, but it seems like a backend issue that this data is missing in the first place.

This appears to have changed on the **MATIC-USD EMA on Quickswap** strategy as of 27.02.2023. Prior to that date, position stats were correctly populated. The other strategies seem fine.
http://tradingstrategy.ai/strategies/quickswap-matic-usd-ema/closed-positions

**Comment by miohtama** [comment]
@AlexTheLion123 Investigate the cause for this

**Comment by AlexTheLion123** [comment]
Could be related #251, see similar issue #250

**Comment by kenkunz** [comment]
Looking at the [closed positions index](http://tradingstrategy.ai/strategies/quickswap-matic-usd-ema/closed-positions) and reviewing various [position details pages](https://tradingstrategy.ai/strategies/quickswap-matic-usd-ema/closed-positions/39), it appears that the position statistics are now all populated correctly.

I'm guessing this can be closed – unless perhaps some additional investigation into root cause is warranted.

**Comment by miohtama** [comment]
@AlexTheLion123 Can you check if this is fixed or not?
