### ISSUE TITLE
Script for clearing frozen positions

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#248]
See #247.

In addition to addressing the immediate issue, it would be nice to have semi-automated way to clear / fix frozen positions.

Can we add a script or API endpoint for this? A script is probably the easier place to start since afaik our APIs are all public / don't currently have any form of auth.

CC: @miohtama, @hieuh25, @AlexTheLion123

**Comment by AlexTheLion123** [comment]
@miohtama Still relevant?

**Comment by miohtama** [comment]
Fixed with a next iteration of trade-executors.
