### ISSUE TITLE
Populate all metadata on startup

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#251]
# Goal

Currently, some `metadata` statistics are only calculated and populated on rebalance. If a strategy crashes or needs to be restarted, this can leave some data empty or incorrect. This data should also be populated on startup.

See https://github.com/tradingstrategy-ai/frontend/issues/393#issuecomment-1462453286 for relevant discussion on this, as well as #250.

**Comment by AlexTheLion123** [comment]
Could fix (potentially):

- [ ] https://github.com/tradingstrategy-ai/trade-executor/issues/250
- [ ] https://github.com/tradingstrategy-ai/frontend/issues/393
- [ ] https://github.com/tradingstrategy-ai/trade-executor/issues/240

**Comment by miohtama** [comment]
Might be coming with Enzyme integration to trade-executor with other related changes
