### ISSUE TITLE
validate mid_price calculations

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#253]
There are buy and sell mid_price calculations for Uniswap V2 and Uniswap V3. Verify them. Example:

https://github.com/tradingstrategy-ai/trade-executor/blob/7a18cc99a8344f780294d48d667d2ec5a7745af5/tradeexecutor/ethereum/uniswap_v3_live_pricing.py#L222-L231

**Comment by hieuh25** [comment]
I think this looks ok, though note that this formula is a bit different than the one used in backtest, e.g: https://github.com/tradingstrategy-ai/trade-executor/blob/196f57daed94755cbdff04118788a4bd6146bea7/tradeexecutor/backtest/backtest_pricing.py#L146-L147
