### ISSUE TITLE
rename `PositionSummary` statistics

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#268]
See [this branch](https://github.com/tradingstrategy-ai/trade-executor/tree/stats-fix) and PR https://github.com/tradingstrategy-ai/trade-executor/pull/261

**Comment by AlexTheLion123** [comment]
Also rename `TradeSummary` to `PositionSummary`

**Comment by AlexTheLion123** [comment]
To be done for updated production frontend

**Comment by miohtama** [comment]
Let's close this now and revisit later with major rewrite.
