### ISSUE TITLE
`load_all_data` vs `load_partial_data`

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#336]
from @EAntsa :

"load_all_data and load_partial_data parameter naming, order and default values do not match. time_frame vs time_bucket, with_liquidity vs liquidity, stop_loss_time_frame vs stop_loss_time_bucket, etc.

load_all_data(client, time_frame, execution_context, universe_options, with_liquidity=True, liquidity_time_frame=None, stop_loss_time_frame=None)

load_partial_data(client, execution_context, time_bucket, pairs, universe_options, liquidity=False, stop_loss_time_bucket=None, required_history_period=None, start_at=None, end_at=None, name=None)"

See [this thread](https://discord.com/channels/888448459168948284/1106234309259571250)

**Comment by AlexTheLion123** [comment]
@miohtama Changing one of these to match the other would involve changes to a couple notebooks. Nothing major, but just confirming that I should still make this breaking change. 

cc @EAntsa

**Comment by miohtama** [comment]
Let's close this and fix this in a next version of backtesting framework, with more incompatible rewrites.

**Comment by miohtama** [comment]
You are going to need `load_all_data` if you do a trading strategy over all tradeable pairs (>30)
