### ISSUE TITLE
Improve integration tests

### ISSUE THREAD

**Issue by hieuh25** [tradingstrategy-ai/trade-executor#35]
Currently most part of the integration tests are using full datasets from API, which grow larger everyday. The most recent build took more than 1 hour to complete in CI.
The tests should be improved by using new JSONL endpoint and smaller datasets:

- Make sure `load_all_data()` is not used anywhere
- Make sure the downloaded data are cached

**Comment by miohtama** [comment]
Breakdown:

- First print out test durations using pytest plugin
- Address slowest tests first

**Comment by hieuh25** [comment]
Slowest tests can be listed by running pytest with: `pytest --durations=0`

**Comment by miohtama** [comment]
Most of the test slowness comes / came from Ganache based tests that are very slow and flaky, as they connect to the real node. I have eliminating them.

I also moved a lot of tests 4h ->  1d candles that has helped the issue a bit.

There might be some other slow tests left, but it is now tolereable.
