### ISSUE TITLE
Invest why stop loss when states made profit

### ISSUE THREAD

**Issue by sontn1988** [tradingstrategy-ai/trade-executor#351]
## GOAL 
Something in this math is not right as it states it made 0.6% profit on a losing trade that hit stop loss
<img width="1340" alt="image" src="https://github.com/tradingstrategy-ai/trade-executor/assets/9410586/4329e5f1-994f-42f9-a134-94b3f959cf18">

**Comment by AlexTheLion123** [comment]
@miohtama Likely related to an ongoing issue where all profits % on the frontend are way off. @miohtama is investigating
