### ISSUE TITLE
stop loss ATR

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#368]
We now support stop loss percentages, usd value, and trailing stop loss. One thing left is ATR (average true range), which is an industry standard.

**Comment by AlexTheLion123** [comment]
No extra support needs to be added for this. Can simply be done in the notebooks with `pandas_ta` and `stop_loss_usd`

E.g. 

```python
import pandas_ta as ta

...

atr_series = candles.ta.atr(length=14)
atr_latest = atr_series.iloc[-1]

...

new_trades = position_manager.open_1x_long(
                pair, 
                buy_amount, 
                stop_loss_usd=float(price_latest - atr_latest)
            )

...

visualisation.plot_indicator(timestamp, "average true range", PlotKind.technical_indicator_detached, atr_latest, colour="purple") 
```

Check out http://176.9.32.86:10000/lab/tree/pancake-eth-usd-indicators.ipynb

**Comment by miohtama** [comment]
Maybe an example in the documentation is enough
