### ISSUE TITLE
live strategy charting for multipair

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#378]
### Problem

Currently, multipair strategies show this in Discord:

`⚠️ Charts not yet available for this strategy type`

### Proposed solution

- We can just display 3 stacked charts if number of pairs <= 3
- If more then we need probably to figure out new solution

**Comment by miohtama** [comment]
@AlexTheLion123 Can you open a ticket for pairs > 3 charts as well - needs more brainstorming how to visualise
