### ISSUE TITLE
Include current day in metadata chart data

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#387]
# Goal

As an investor browsing trading strategies, I want the chart displayed on strategy index page tiles to include the current day (in-progress) performance value.

<img width="1430" alt="image" src="https://github.com/tradingstrategy-ai/trade-executor/assets/35901/707eb738-2597-4ea6-a3c2-ecbe67abe5f8">

## Details

In order to include current day performance on the strategy tile, the current day (in-progress) value needs to be added to the `metadata` payload.

See [Discord thread](https://discord.com/channels/888448459168948284/1118175070058184764).

## Possible approaches

Here are two possible approaches to providing this data, with a trade-off between implementation simplicity vs. purity of data semantics.

### 1. Append current day % change to end of `performance_chart_90_days`

The simplest way to have the strategy tile chart include this data is to append the in-progress current day value to the end of `performance_chart_90_days`, with a timestamp (first value of tuple) of midnight tomorrow UTC. Using this timestamp ensures that the items in the performance chart array reflect the same time bucket / delta (currently daily with all values at midnight UTC).

While this approach is simple from a technical implementation perspective, it may be somewhat confusing and inconsistent from a data semantics perspective. All other items in this array (should) reflect a final, immutable value with a date in the past. The last element in this array would now have special semantics in that it is mutable and a future date.

### 2. Add `current_day_performance` to `summary_statistics`

This approach addresses the data semantics inconsistency described above. Instead of appending this value to `performance_chart_90_days`, add a new property to `summary_statistics` that represents the same type of relative performance value found in the chart data, for the current day (in-progress).

In order to include this data point in the strategy tile chart, `frontend` will need to manually append this value to the end of `performance_chart_90_days` with a timestamp of midnight tomorrow UTC. This requires a minimal amount of additional logic on `frontend`, while preserving better consistency / purity of data semantics.

**Comment by AlexTheLion123** [comment]
@kenkunz Just checking still relevant before I go ahead with this?

**Comment by kenkunz** [comment]
> @kenkunz Just checking still relevant before I go ahead with this?

_Yes_

I think option 2 above is the better approach – it doesn't add much work for `frontend`, and keeps the data semantics more consistent.

Looking at the existing data, I wonder if `summary_statistics.profitability_90_days` is the correct value for this? Or perhaps that will only be the right value if the strategy has been running < 90 days?

I also looked at `key_metrics.profitability` but that appears to be different than the data in `summary_statistics.performance_chart_90_days`.

**Comment by miohtama** [comment]
@miohtama export the incomplete day data in the performance chart

**Comment by AlexTheLion123** [comment]
@miohtama Would the best approach to getting the current day data be to *check if position(s) was opened in the after midnight, and including the realised profitability for these?

**Comment by miohtama** [comment]
The question is between realised profitability vs. unrealised profitability.

Let's close this and move to "WONTFIX"
