### ISSUE TITLE
live strategy charting for more than 3 pairs

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#395]
incorrectly moved to done

**Comment by miohtama** [comment]
Check if something went wrong in merge

**Comment by AlexTheLion123** [comment]
working on frontend but forget to add logic to get discord working

**Comment by AlexTheLion123** [comment]
should be fixed, but will have to see after multipair strategy is restarted on latest trade-executor

**Comment by AlexTheLion123** [comment]
This is for more than 3 pairs, so unworked on yet!
