### ISSUE TITLE
Chart data and summary metrics out-of-sync

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#403]
# Issue

@tsorro [pointed out](https://discord.com/channels/888448459168948284/1042719707037450240/1122496414128275496) that the chart data and summary metrics on **ETH-USD long strength on Uniswap v3** are out of sync.

For example, **Realized profit** does not seem to match the loss shown in the chart. **Return %** and **Annualized return %** are blank.

https://tradingstrategy.ai/strategies/enzyme-polygon-eth-usdc-sls/performance
<img width="978" alt="image" src="https://github.com/tradingstrategy-ai/trade-executor/assets/35901/8a1a1610-52bf-4e36-a182-520bc28cd998">

**Comment by miohtama** [comment]
@AlexTheLion123 can you double check this one if this still the case
