### ISSUE TITLE
compound annualised return or not?

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#410]
Not totally sure about the details, will need more clarification from @miohtama @EAntsa. [See thread](https://discord.com/channels/888448459168948284/1123270940927733963)

**Comment by AlexTheLion123** [comment]
So this is basically whether to return `APR` vs `APY`?

**Comment by miohtama** [comment]
Both preferred

**Comment by AlexTheLion123** [comment]
@miohtama can we close? Now using CAGR

**Comment by miohtama** [comment]
Fixing this by adding CAGR as KeyMetric in the trade-executor API
