### ISSUE TITLE
`visualisation` endpoint fails when `type=large`

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#482]
# Issue

The `/visualisation` endpoint for any strategy return an error when `type=large`.

#### 1. load `/visualisation` with no type or `type=small`
[click here to load](https://enzyme-polygon-eth-usdc.tradingstrategy.ai/visualisation)
<details>
<summary>note that the image loads correctly</summary>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/35901/256031307-6eeec8ca-6f57-445e-82b7-591cfb0e872a.png"><img src="https://user-images.githubusercontent.com/35901/256031307-6eeec8ca-6f57-445e-82b7-591cfb0e872a.png" alt="image" style="max-width: 100%;"></a>
</details>
   
#### 2. load `visualisation` with `type=large`
[click here to load](https://enzyme-polygon-eth-usdc.tradingstrategy.ai/visualisation?type=large)
<details>
<summary>note error</summary>
<a target="_blank" rel="noopener noreferrer" href="https://github.com/tradingstrategy-ai/trade-executor/assets/35901/5ba71534-ec26-49ba-bdd7-14d398d29cf3"><img src="https://github.com/tradingstrategy-ai/trade-executor/assets/35901/5ba71534-ec26-49ba-bdd7-14d398d29cf3" alt="image" style="max-width: 100%;"></a>
</details>

## Impact

The **Decision making** tab on `frontend` currently makes use of this endpoint using `type=large`. This chart is therefore not displaying for any strategies.

This visualisation is useful to investors and strategy developers to understand key metrics used to determine when a strategy executes a trade.

**Comment by kenkunz** [comment]
CC: @AlexTheLion123

**Comment by AlexTheLion123** [comment]
should hopefully closed by PR similar to #503
