### ISSUE TITLE
PandasTraderRunner tests

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#486]
Tests needed for this class, especially for `refresh_visualisations` and `report_strategy_thinking`

**Comment by AlexTheLion123** [comment]
Tests for `report_strategy_thinking` may be difficult since it posts to discord, leaving out for now, just doing for `refresh_visualisations`

**Comment by AlexTheLion123** [comment]
Actually, test coverage does include `report_stratgy_thinking`, but no assertions for this

**Comment by miohtama** [comment]
This is ok, we cannot test this easily.
