### ISSUE TITLE
Reduce boilerplate

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#49]
We should aim to make the trade-executor library as accesible as possible, without sacrificing use cases for advanced users. Currently, there is a lot of boilerplate code that can be hidden from retail users who don't require a high degree of customization. This can be done by building a wrapper library on top of the current library or adjusting the current library.

**Comment by AlexTheLion123** [comment]
@miohtama Time to revisit this again?

**Comment by miohtama** [comment]
Let's close this and fix this in a next version of backtesting framework, with more incompatible rewrites.

**Comment by AlexTheLion123** [comment]
@miohtama  Time to revisit?

**Comment by AlexTheLion123** [comment]
Seems like notebooks are stable for now.
