### ISSUE TITLE
Update  `icon_url` to match strategy id

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#571]
# Goal

As a `frontend` developer, I want strategies to use a consistent pattern for their `icon_url` values, so that I can add strategy icon images.

## Background

Currently, most strategies have the following `icon_url` value:
```
https://tradingstrategy.ai/avatars/eth-usd-breakout-uniswap-v3.jpg
```

The one exception to this is `polygon-multipair-momentum` which points to an image hosted on `files.gitbook.io`.

By changing **all** strategies to use a consistent pattern under the `/avatars` directory on `frontend`, it will make it much easier to host appropriate, unique icon images for each strategy.

## Acceptance criteria

- each strategy's `icon_url` value (which is included in the `/metadata` endpoint) uses the following pattern:
  ```
   https://tradingstrategy.ai/avatars/(strategy_id).jpg
  ```
  for example: `enzyme-polygon-matic-usdc` strategy has `icon_url` value of:
  ```
   https://tradingstrategy.ai/avatars/enzyme-polygon-matic-usdc.jpg
  ```
- future strategies may still use a custom `icon_url` value that does not follow this pattern – e.g., strategies not hosted by Trading Strategy

**Comment by AlexTheLion123** [comment]
Doesn't use https until [this PR](https://github.com/tradingstrategy-ai/trade-executor/pull/958) merged

**Comment by AlexTheLion123** [comment]
@kenkunz The strategy mentioned here seems to be no longer available, so closing
