### ISSUE TITLE
Inaccurate performance data on `polygon-multipair-momentum`

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#575]
# Issue

The performance data shown both on the [strategy index page](http://localhost:5173/strategies) and the [strategy performance page](http://localhost:5173/strategies/polygon-multipair-momentum/performance) is inconsistent with the actual performance of the strategy based on its trades.

## Steps to reproduce

1. View _Open-ended momentum strategy for Polygon_ on [strategy index](http://localhost:5173/strategies) page
   - note the jump in value between 2020-09-20 and 2020-09-21 (from `-6.7%` to `22.6%`)
      - _side note: the date shown in the chart hover display is off by one day – see tradingstrategy-ai/frontend#596_
   - view the data used by the chart: [polygon-multipair-momentum/metadata](https://polygon-multipair-momentum.tradingstrategy.ai/metadata)
   - note the same jump in value between data points with ts `1695168000` and `1695254400`
3. View the [performance page](http://localhost:5173/strategies/polygon-multipair-momentum/performance) for _Open-ended momentum strategy for Polygon_
   - note a similar jump in value on 2023-09-21
   - view the data used by the chart: [polygon-multipair-momentum/chart](https://polygon-multipair-momentum.tradingstrategy.ai/chart?type=compounding_realised_profitability&source=live_trading)
   - note the jump in value between data points with ts `1695294463` and `1695299117`
4. View the [closed positions page](https://tradingstrategy.ai/strategies/polygon-multipair-momentum/closed-positions) for this strategy
   - note there have only been losing positions during this timeframe

## Potential cause

Note that there's a frozen position [Position #53](https://tradingstrategy.ai/strategies/polygon-multipair-momentum/frozen-positions/53) with trades during the same timeframe. In particular, the last trade (which failed to execute) shows a very inflated value. Not sure how the performance data is calculated… but perhaps this position has something to do with it?

**Comment by AlexTheLion123** [comment]
@miohtama Can close?
