### ISSUE TITLE
State class needs to be changed to support multiple visualisations

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#58]
The state class appears to support multiple trading pairs through the portfolio and its other methods, but not through the visualisations. Every trading pair should be able to have a separate visualisation. 

https://github.com/tradingstrategy-ai/trade-executor/blob/a1bc30368bfd105b58e762431e70d8f9d17715c3/tradeexecutor/state/state.py#L51

**Comment by miohtama** [comment]
The visualisation should internally support multiple pairs: any indicator within the visualisation such know which the pair to which it belongs. It is only the master singleton that captures all visualisation data of strategies. If this is not the case we need to add pair id and name tracking to indicators. 

However, if the trading strategies are not correlated, as when testing the same strategy over multiple pairs, each pair should produce its own state and visualisation (states are comparable)
