### ISSUE TITLE
Missing Uniswap V3 volume data in backtesting

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#629]
Apparently Uniswap V3 volume data is available on the backend, however, it is not available on during backtesting. Make available.

**Comment by miohtama** [comment]
Make sure there is at least one example in the documentation to show the volume.

**Comment by AlexTheLion123** [comment]
TODO: 

- [ ] add to docs

**Comment by AlexTheLion123** [comment]
https://tradingstrategy.ai/docs/programming/code-examples/uniswap-v3-data.html
