### ISSUE TITLE
Add tooltips to summary table headings

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#635]
### Goal

As a strategy developer, I want to see tooltips to summary table row headings so that I can easily find more information about a statistic.

### Acceptance criteria

- [ ] Any statistic that may need further explanation has a tooltip
- [ ] This applies to the long only table and the long-short table
- [ ] Tooltip for value at end statistic (does it include realised/unrealised profits)

**Comment by miohtama** [comment]
Make sure it works on the documentation site as well.

Post link to a documentation where it is being used.

**Comment by AlexTheLion123** [comment]
TODO: add to docs

**Comment by AlexTheLion123** [comment]
First want #640 to be fixed

**Comment by AlexTheLion123** [comment]
This should be fixed now, can go ahead
