### ISSUE TITLE
profit reporting for long/short summary stats

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#640]
- [x] Fix return % for long and short
- [ ] Realised profits should add up to value at end, since no open positions at the end

![Image](https://github.com/tradingstrategy-ai/trade-executor/assets/74208897/e793074b-ff04-440c-9b3b-756c83761bcb)

**Comment by AlexTheLion123** [comment]
Need some help from @hieuh25 for second point

**Comment by miohtama** [comment]
Let's keep this open, the bug is still out there.

**Comment by AlexTheLion123** [comment]
The percentages also seem to be way off in sideloading

**Comment by miohtama** [comment]
Fixed in https://github.com/tradingstrategy-ai/trade-executor/commit/15a2bd9513f3ddfc5e5e01a1d4ba4e4e9fccc9e4
