### ISSUE TITLE
trade analyser max position size bug

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#66]
get_max_size() method in analysis/trade_analyser.py contains a bug that includes both buys and sells as positive

**Comment by hieuh25** [comment]
Reopen as the fix in #67 is only temporary, it doesn't work correctly when a position has more than 2 trades, it can be finalized later

**Comment by miohtama** [comment]
Only topical after we have strategies that increase or decrease positions by steps.

**Comment by AlexTheLion123** [comment]
Help requested from @hieuh25

**Comment by AlexTheLion123** [comment]
After conversation with @hieuh25, seems like the right to do this is:

```python
def get_max_size(self) -> USDollarAmount:
        """Get the largest size of this position over the time"""
        cur_size = 0
        max_size = 0

        for t in self.trades.values():
            if t.is_buy():
                cur_size += t.value
            else:
                cur_size -= t.value
            
            max_size = max(cur_size, max_size)
            
        return max_size
```
