### ISSUE TITLE
Open position value inconsistent with open position list

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#662]
# Issue

On at least one occasion, the open position value shown on the strategy performance page did not match the value of actual open positions shown on the open positions page.

## Details

@tsorro reported this [on Discord](https://discord.com/channels/888448459168948284/966616449311465504/1173348179882819624) at `2023-11-12 19:46 UTC`:

> We have some inconsistencies in the strategy dashboard. 
> Performance tab shows there is an open position worth $351.09 but the open positions list is empty. 
> It's probably the latest closed position which is missing value data on the closed positions list 
> https://tradingstrategy.ai/strategies/enzyme-polygon-multipair/performance
> <img src="https://github.com/tradingstrategy-ai/trade-executor/assets/35901/3694df00-8797-4613-bdf4-2c4e25392520" width="200"> <img src="https://github.com/tradingstrategy-ai/trade-executor/assets/35901/df4bf421-ce00-4eac-82b7-95ec48e06fac" width="200"> <img src="https://github.com/tradingstrategy-ai/trade-executor/assets/35901/629df0e1-1ddd-4157-8414-44ad6a1fddfd" width="200"> <img src="https://github.com/tradingstrategy-ai/trade-executor/assets/35901/f2d2c095-632e-4561-a40c-b515d7654b87" width="200">
>
> It's this MATIC position that triggered trailing stop loss 
> <img src="https://user-images.githubusercontent.com/35901/282509951-569bfe95-be05-447e-970b-3b40586dea4d.png" alt="image" width="200">

## `frontend` investigation

The source used by `frontend` for both elements (open position value and list of open positions) is the `state` endpoint (uncached). Specifically:
- `state.stats.portfolio.at(-1).open_value`
- `state.positions.open_positions`

## `trade-executor` investigation

Investigate whether the data in the most recent `state.stats.portfolio` entry can lag behind `state.positions.open_positions`, and if so, how this can be fixed.

**Comment by miohtama** [comment]
@AlexTheLion123 Can you double confirm if this is fixed now

**Comment by miohtama** [comment]
Likely fixed with the latest updates of inconsistency in profit values and such
