### ISSUE TITLE
Broken performance chart for polygon momentum multipair

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#667]
The [performance chart](https://tradingstrategy.ai/strategies/polygon-multipair-momentum/performance) (green chart) for [Polygon momentum multipair strategy](https://tradingstrategy.ai/strategies/polygon-multipair-momentum) shows a very large increase in profit on October 25th, which corresponds to some large withdrawal and deposit action ([red chart](https://tradingstrategy.ai/strategies/polygon-multipair-momentum/netflow)) around this time. The calculation is likely confusing these deposits and withdrawals in the profit calculation as there were no trades around this time that can account for such substantial profit

![Image](https://github.com/tradingstrategy-ai/trade-executor/assets/74208897/0c2c872f-ea96-4fa1-b106-333d0551098b)

![Image](https://github.com/tradingstrategy-ai/trade-executor/assets/74208897/764cea63-30a2-4534-a84e-7235039099ce)

**Comment by miohtama** [comment]
Let's wait for frontend strategy page update.

**Comment by miohtama** [comment]
Caused by a deposit event. Figure out how.

**Comment by AlexTheLion123** [comment]
Will save latest state file to scratchpad and restart strategy with proper weekly cycles. Hopefully this problem does not resurface.

**Comment by AlexTheLion123** [comment]
This strategy has been restarted with weekly cycles, @miohtama can we close?
