### ISSUE TITLE
very high sharpe and sortino ratios on frontend

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#697]
### Summary

Across the board, our current Sharpe and Sortino scores are surprisingly high on the [live strategies](https://tradingstrategy.ai/strategies). Are we sure the math behind these is correct?

In particular, [polygon momentum multipair](https://tradingstrategy.ai/strategies/polygon-multipair-momentum) strategy currently has a Sharpe of 9.98 and Sortino of 31.80, seemingly non-sensical values.

See [message](https://discord.com/channels/888448459168948284/1179658741067567114/1179750557188100196) from @tsorro 

### Risk Underestimation

A high Sharpe ratio could suggest that the risk (volatility) of the portfolio has been underestimated. This might happen due to a miscalculation of the standard deviation of returns or due to a limited dataset that does not adequately capture the range of potential market conditions.

### Acceptance criteria

- As Sharpe and Sortino ratios are considered very good at around 3, the corrected values should be closer to this. Anything significantly more than this should be viewed with much scepticism.

**Comment by miohtama** [comment]
@miohtama these numbers need to be still revisited

**Comment by miohtama** [comment]
The backtesting period forthe strategy is too short

- Set `backtest_start` and `backtest_end` in the strategy module
- Re-run `trade-executor backtest` command


![Image](https://github.com/tradingstrategy-ai/trade-executor/assets/49922/d2428552-0696-4fb2-a3c1-368a85d5d624)

**Comment by AlexTheLion123** [comment]
After increasing the backtesting period, the profitability is very bad and the sharpe and sortino values are now very low. Note that this is not the intended use for the strategy. Orginally, it was supposed to trade only weekly, which was profitable on backtesting, but for testing purposes, we made it trade much more frequently.

**Comment by AlexTheLion123** [comment]
Discussing further with @tsorro

**Comment by AlexTheLion123** [comment]
Discussing further with @tsorro

**Comment by AlexTheLion123** [comment]
Discussing further with @tsorro

**Comment by AlexTheLion123** [comment]
Discussing further with @tsorro
