### ISSUE TITLE
Add long/short stats to state payload

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#706]
### Summary

- Frontend requires additional statistics for overall/long/short to further highlight the strategy's differing performances between long and short
- The frontend should receive every data point as pre-formatted data i.e. as strings
- Where applicable, links to the glossary definition should be included in the payload

### Proposed API

JSON serializable array of objects where each element has the following attributes: 

1. value - final value of the data point, represented as a string e.g. "5.00%" 
2. name - name of the statistic e.g. "Take profits triggered"
3. "label" - can be one of "overall", "long", or "short"
4. "glossary_link" - link to the glossary definition in the documentation e.g. https://tradingstrategy.ai/glossary/take-profit

E.g. 
```json
[{
"value": "5",
"name": "Take profits triggered",
"label": "short",
"glossary_link": "https://tradingstrategy.ai/glossary/take-profit"
}]
```

**Comment by AlexTheLion123** [comment]
@kenkunz Yeah that makes sense, will do

**Comment by miohtama** [comment]
When we do multi-column presentation we can think that each metric is a row. Thus the value of the row is the cells.

This makes the data more parseable and understandable:

```
[{
"value": {"All": 1, "Short": 2, "Long": 3},
"name": "Take profits triggered",
"label": "short",
"glossary_link": "https://tradingstrategy.ai/glossary/take-profit"
}]

**Comment by AlexTheLion123** [comment]
@miohtama So the rows argument in the `StatisticsTable` would look like, as an example:


```python
rows = dict(
  KeyMetricKind.trading_period_length: (list of 3 key metrics for all, long, and short), 
  ...
  ...
)
```

**Comment by miohtama** [comment]
The rows should look like

rows = {
    KeyMetricKind.trading_period_length: KeyMetrics(value={"All": 10, "Short": 10, "Long:" 10}, name="Trading Period Length", ....)
    ....
}

**Comment by AlexTheLion123** [comment]
@miohtama 

@miohtama I have the function for calculating long/short metrics (https://github.com/tradingstrategy-ai/trade-executor/blob/536aa8efa890f3edbb93041814065e029b2b110f/tradeexecutor/statistics/key_metric.py#L334), 

I'm wondering now where to use it. Is it fine to yield all the key metrics as part of `calculate_key_metrics`, like this: https://github.com/tradingstrategy-ai/trade-executor/blob/536aa8efa890f3edbb93041814065e029b2b110f/tradeexecutor/statistics/key_metric.py#L301-L302

Maybe it's better to add the table an additional attribute to of `StrategySummaryStatistics` class?

**Comment by miohtama** [comment]
I think it's nicer to return `DataFrame` from ` calculate_long_short_metrics` and then convert this to `KeyMetric` table in a separate function. This is because you likely want to display `DataFrame` directly in the notebook and `KeyMetric` is a convention just for the frontend.

**Comment by AlexTheLion123** [comment]
@miohtama Howcome we want to return DataFrame from `calculate_long_short_metrics`? Because [`calculate_all_summary_stats_by_side`](https://github.com/tradingstrategy-ai/trade-executor/blob/a800c9f9800467c48e0e52518bab26354279add5/tradeexecutor/analysis/trade_analyser.py#L905) can already return a dataframe with all those stats.

**Comment by AlexTheLion123** [comment]
@miohtama I currently have `serialise_summary_statistics_as_json_table()` at the end of `calculate_key_metrics()` like so: 

```python
long_short_table = serialise_summary_statistics_as_json_table(source_state, source)
yield from (row for row in long_short_table.rows.values())
```

I originally thought it would be nice to use it outside of `calculate_key_metrics()`, but this function does certain checks to `live_state` and `backtested_state` to determine which is the correct source state to use. So, the `calculate_key_metrics` API would have to be changed to:

```python
def calculate_key_metrics(
  source_state: State,
  calculation_window_start_at,
  calculation_window_end_at,
  freq_base: pd.DateOffset = pd.offsets.Day(),
)
```

From the original (for reference):

```python
def calculate_key_metrics(
  live_state: State,
  backtested_state: State | None = None,
  required_history = datetime.timedelta(days=90),
  freq_base: pd.DateOffset = pd.offsets.Day(),
)
```

This would only involve [one change](https://github.com/tradingstrategy-ai/trade-executor/blob/41078ba630781c3d4c5081444c2609c8a54d4a2b/tradeexecutor/statistics/summary.py#L122) in the codebase and some changes in the [`test_summary_and_metrics](https://github.com/tradingstrategy-ai/trade-executor/blob/master/tests/test_summary_and_metrics.py) module

**Comment by miohtama** [comment]
I think it's better to make a new function altogether, as this will break existing code. `calculate_key_metrics` is not very long.
