### ISSUE TITLE
Improve web server performance & scalability

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#707]
# Goal

As a client of `trade-executor` HTTP endpoints, I want to get responses in a reasonable amount of time, so that the service is responsive and usable.

## Details

While working on some `frontend` tickets, I was encountering errors after multiple concurrent requests to `trading-strategy` endpoints. The errors turned out to be client-side timeouts, due to the long response times from the service when it is handling more that 1 concurrent request.

Here is an example request to a slow endpoint (`chart`). Note that when handling multiple concurrent requests, all of the responses are delayed almost equally and then return in short succession after the delay. The times given in the table below are for the last/slowest response, but the other requests in that run had similar times.

```bash
curl -i 'https://enzyme-polygon-matic-usdc.tradingstrategy.ai/chart?type=total_equity&source=live_trading' -s -o /dev/null -w  "\n%{time_starttransfer}\n"
```

| Concurrent<br>Requests | Response<br>Time |
| ---: | ---: |
| 1 | 5.4s |
| 2 | 15.6s |
| 3 | 22.0s |
| 4 | 33.5s |
| 5 | 36.9s |

## Acceptance Criteria

1. Handle up to 100 concurrent requests with minimal degradation of response times.

**Comment by AlexTheLion123** [comment]
@kenkunz @miohtama can we close? seems much faster now
