### ISSUE TITLE
Unused calculate_summary_statistic() calls

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trade-executor#71]
https://github.com/tradingstrategy-ai/trade-executor/blob/5a722ad53283f065a60b9133500b7b20c98ee296/tradeexecutor/statistics/core.py#L49

https://github.com/tradingstrategy-ai/trade-executor/blob/5a722ad53283f065a60b9133500b7b20c98ee296/tradeexecutor/statistics/core.py#L64

These two lines currently take up 36% up backtest running time and aren't even used. The strategy notebooks simply calculate summary statistics at the end.

**Comment by miohtama** [comment]
See discussion in PR.
