### ISSUE TITLE
Strategy charts show inconsistent data

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#725]
# Issue

The "ETH mean reversion bounce" strategy was deployed to `frontend` on `2023-12-18`. For this strategy, the performance chart shown on the index view is inconsistent with the one displayed on the strategy overview page.

> [!Note]
> Initially it appeared that the issue may be due to an inconsistency in the chart data rollup logic on `frontend`. After further investigation, it appears that the inconsistency is with the data itself (from `metadata` vs. `chart` endpoints). See API repro and data comparison below.

## Steps to reproduce (UI)

1. Open [strategy index page](https://tradingstrategy.ai/strategies)
2. Open ETH mean reversion bounce [overview page](https://tradingstrategy.ai/strategies/polygon-eth-spot-short)
3. Note difference between charts
   - expected: charts are consistent
   - actual: index page chart shows downward trend line; overview page chart shows static line with no trend

<table>
<thead>
<tr>
<th>Index page</th>
<th>Overview page</th>
</tr>
</thead>
<tbody>
<tr>
<td width="35%">
<img width="100%" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/70abbd8c-6803-41fe-88b3-9a1e0d85a2f3">
</td>
<td width="65%">
<img width="100%" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/451c1efa-0969-4f5d-81fa-1c522a121981">
</td>
</tr>
</tbody>
</table>

## Steps to reproduce (API)

1. Fetch the `metadata` endpoint for `polygon-eth-spot-short`:
   - [metadata](https://polygon-eth-spot-short.tradingstrategy.ai/metadata) ← open link in new tab
2. Fetch the `chart` endpoint for `polygon-eth-spot-short` (`type=compounding_realised_profitability` `source=live_trading`)
   - [chart](https://polygon-eth-spot-short.tradingstrategy.ai/chart?type=compounding_realised_profitability&source=live_trading) ← open link in new tab
3. Compare the dates and values between `performance_chart_90_days` array from `metadata` and `data` array from `chart`:
   - expected: although the data points are not identical (the `chart` elements represent specific, arbitrary date/times, while the `metadata` chart elements are normalized and rolled up to days) – the values should be consistent
   - actual: the values are inconsistent (see table below)

### API data for comparison

The following table shows the data from both sources, merged and sorted by date. This helps make the inconsistency apparent:
- in row idx `3`, the `chart` data becomes non-zero as of `2023-12-16T10:05:38.000Z`
- in row idx `7`, the `metadata` data is still zero as of `2023-12-18T00:00:00.000Z`
- rolling the `chart` data up to any normalized time unit of `1h` or greater causes all `0` data points from that data set to be lost, since rows `1` through `5` all occur within the same hour; this is why the chart on the strategy overview page does not show any downward trend.

| idx | source | Unix ts | ISO date | value |
| --- | --- | --- | --- | ---: |
| 0 | metadata | `1702684800` | `2023-12-16T00:00:00.000Z` | `0` |
| 1 | chart | `1702721003` | `2023-12-16T10:03:23.000Z` | `0` |
| 2 | chart | `1702721104` | `2023-12-16T10:05:04.000Z` | `0` |
| 3 | chart | `1702721138` | `2023-12-16T10:05:38.000Z` | `-1.4168024531358014e-9` |
| 4 | chart | `1702721918` | `2023-12-16T10:18:38.000Z` | `-1.4168024531358014e-9` |
| 5 | chart | `1702721944` | `2023-12-16T10:19:04.000Z` | `-2.6314989076681172e-9` |
| 6 | metadata | `1702771200` | `2023-12-17T00:00:00.000Z` | `0` |
| 7 | metadata | `1702857600` | `2023-12-18T00:00:00.000Z` | `0` |
| 8 | metadata | `1702944000` | `2023-12-19T00:00:00.000Z` | `-2.6314989076681172e-9` |
| 9 | chart | `1703025540` | `2023-12-19T22:39:00.000Z` | `-2.6314989076681172e-9` |

**Comment by AlexTheLion123** [comment]
the charts seem to be identical now
