### ISSUE TITLE
Inconsistent "Age" and "Trading period length" metrics

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#787]
# Issue

The **Age** metric shown on the [strategy index](https://tradingstrategy.ai/strategies) and [overview](https://tradingstrategy.ai/strategies/enzyme-polygon-eth-usdc) pages differs from the live trading data **Trading period length** metric shown on the [performance page](https://tradingstrategy.ai/strategies/enzyme-polygon-eth-usdc/performance) table.

For example, at the time of this ticket submission on **ETH-USD breakout** strategy linked above, the values are 224 days and 217 days respectively.

## Details

| | Age | Trading period length |
| --- | --- | --- |
| **Used on:** | strategy [index](https://tradingstrategy.ai/strategies) and [overview](https://tradingstrategy.ai/strategies/enzyme-polygon-eth-usdc) | strategy [performance page](https://tradingstrategy.ai/strategies/enzyme-polygon-eth-usdc/performance) |
| **Endpoint:** | `metadata` | `state` |
| **Path:** | `summary_statistics` . `key_metrics` . `started_at`  | `stats` . `long_short_metrics_latest` . `live_stats.rows` . `trading_period_length` . `value` |

**Comment by AlexTheLion123** [comment]
Yes, they should be the same
